const arr = [
  "Pcos",
  "Leg Pain",
  "Migraine",
  "Depression",
  "Runny Nose",
  "Snoring",
  "Back Pain",
  "Common Cold",
  "Dengue Fever",
  "Diarrhea",
  "Arthritis",
  "Excessive Thirst",
  "Stress",
  "Sinusitis",
  "Fatigue",
  "Gastroenteritis",
  "Obesity",
  "Cold Hands And Feet",
  "Body Pain",
  "Headache",
  "Eating Habits",
  "Vomiting",
  "Cough",
  "Gallstones",
  "Fainting",
  "Shoulder Pain",
  "Chest Pain",
  "Asthma",
  "Sore Throat",
  "Overeating",
  "Malaria",
  "Jaundice",
  "Anxiety",
  "Fibroids",
  "Blocked Nose",
  "Acid Reflux",
  "Bloating",
  "Neck Pain",
  "Diabetes",
  "Dehydration",
  "Nausea",
  "Urinary Tract Infection",
  "Stomach pain",
  "Kidney Stones",
  "Urethroplasty",
  "Hair",
  "Quit Smoking",
  "Leg Sprain",
  "Syphilis",
  "Brain",
  "Lungs",
  "Facebow",
  "Infection",
  "Neck",
  "Scleroderma",
  "Health Check",
  "Cardiomyopathy",
  "Diabetic Retinopathy",
  "Injury",
  "Shingles",
  "Ligament Tear",
  "Colorectal Surgeon",
  "Gall Bladder",
  "Chest",
  "Liver",
  "Trauma",
  "Tongue",
  "Endodontist",
  "Cardiac Catheterization",
  "Swelling Around The Eye",
  "Vaccination",
  "Pediatric Nephrologist",
  "Cardiovascular Surgeon",
  "Cervix",
  "Prolapse",
  "Meningitis",
  "Miscarriage",
  "Feet",
  "Smoking Cessation",
  "Cosmetic Rhinoplasty",
  "Gums",
  "General Physician",
  "Pancreas",
  "Alzheimers Disease",
  "Total Knee Replacement",
  "Genital Tb",
  "Knee Fracture",
  "Andrologist",
  "Head",
  "Bacterial Vaginosis",
  "Hepatitis",
  "Stroma",
  "Burn",
  "Schizophrenia",
  "Typhoid Fever",
  "Prostatectomy",
  "Intestine",
  "Hysterotomy",
  "Influenza",
  "Removal",
  "Nephrologist",
  "Cardiologist",
  "Dermatologist",
  "Getting Weak",
  "Accident",
  "Home Pregnancy Test",
  "Diabetologist",
  "Keratoconus",
  "Toe",
  "Cancer",
  "Spinal Injury",
  "Ear",
  "Irritable Bowel Syndrome",
  "Bone Marrow",
  "Haemophilia",
  "Oral And Maxillofacial Surgeon",
  "General Dentist",
  "X Ray",
  "Pap Smears",
  "Urologist",
  "Biopsy",
  "Spine Surgeon",
  "Disc Herniation",
  "Dental Braces",
  "Cancer Treatment",
  "Face",
  "Strep Throat",
  "Ankle Sprain",
  "Fingers",
  "Supraventricular Tachycardia",
  "Dyspepsia",
  "Tapeworms Infestation",
  "Obstetrician",
  "Endocrinologist",
  "Sexologist",
  "Acne Treatment",
  "Sciatica Treatment",
  "Percutaneous Balloon Pericardiotomy",
  "Radiologist",
  "Throat",
  "Emergency Medicine Specialist",
  "Pediatric Cardiologist",
  "Full Body",
  "Fixed Appliances",
  "Stitching",
  "Skin",
  "Neurologist",
  "Neurosurgeon",
  "Dental Bridge",
  "Motion Sickness",
  "Interventional Cardiologist",
  "Organ Donation",
  "Degenerative Disc Disease",
  "Dietitian",
  "Scaling",
  "Nose",
  "Alchoholic Liver Disease",
  "Spine",
  "Pain While Breastfeeding",
  "Legs",
  "Intra Uterine Device",
  "Vagina",
  "Tonsillitis",
  "Latent Autoimmune Diabetes Of Adults",
  "Cut",
  "Ear Cleaning",
  "Hand Fracture",
  "Gynecologic Endoscopy Surgeon",
  "Sprain",
  "Cosmetic Surgery",
  "Orthodontist",
  "Retina",
  "Leg Fracture",
  "Pediatric Neurologist",
  "Vascular Surgeon",
  "Hematologist",
  "General Surgeon",
  "Reproductive Issues",
  "Acid Lipase Disease",
  "Laproscopic Gynecologist",
  "Mouth Cancer",
  "Tooth Filling",
  "Heart Failure",
  "Eye",
  "Laproscopic Surgery",
  "Keyhole Surgery",
  "Allergy",
  "Coronary Angiography",
  "Abdominoplasty",
  "Fracture",
  "Nerves",
  "Back",
  "Thyroid Gland",
  "Hepatologist",
  "Veneers",
  "Radical Prostatectomy",
  "Pulp Therapy",
  "Pancreatic Stones",
  "Concussion",
  "Obstetric Anal Sphincter Injury",
  "Lumbar Puncture",
  "Nephrectomy",
  "Aids Treatment",
  "Gynae Problems",
  "Urooncologist",
  "Health Checkup",
  "Genital Candidiasis",
  "Disease",
  "Seasonal Depression",
  "Uterus",
  "Wisdom Teeth",
  "Alexander Disease",
  "Respiratory Medicine Specialist",
  "Slipped Disc",
  "Sleep Medicine Specialist",
  "Prostatitis",
  "Muscle",
  "Cornea Transplant",
  "Sexually Transmitted Diseases",
  "Scalp",
  "Colonoscopy",
  "Anus",
  "Dental Crown",
  "Heart",
  "Conjunctivitis",
  "Fibroid Removal",
  "Arrhythmia",
  "Pneumonia",
  "Kidney Infection",
  "Sports Medicine Specialist",
  "Heel",
  "Liver Disease",
  "Bone",
  "Ear Piercing",
  "Internal Medicine Specialist",
  "Diverticulitis",
  "Joints",
  "Blood",
  "Ophthalmologist",
  "Tooth Extraction",
  "Female Sexual Problems",
  "Surgical Sperm Retrival",
  "Lap Band Surgery",
  "Trichomoniasis",
  "Cervical Cancer",
  "Oncologist",
  "Urethra",
  "Kidneys",
  "Influenza Vaccine",
  "Tmj Disorder",
  "Ent Specialist",
  "Lipoma",
  "Joint Replacement",
  "Alcohol Withdrawal",
  "Blisters On Skin",
  "Knee",
  "Root Canal Treatment",
  "Arthroplasty",
  "Hip",
  "Minimal Invasive Surgery",
  "Bone Cancer",
  "Blister On Skin",
  "Tonsils",
  "Urinary Bladder",
  "Minimally Invasive Cardiac Surgery",
  "Doctor",
  "Urosurgeon",
  "Teeth",
  "Ribs",
  "Stomach",
  "Surgery",
  "Gastroenterologist",
  "Aids",
  "Endoscopy",
  "Knee Injury",
  "Reproductive Medicine Specialist",
  "Swine Flu",
  "Maternal Fetal Medicine Specialist",
  "Rheumatologist",
  "Ankle",
  "Body",
  "MRI",
  "Cystectomy",
  "Dental Caries",
  "Arms",
  "Prolactinemia",
  "Abscess",
  "Sinus",
  "Pulmonologist",
  "Psychiatrist",
  "Gastrosurgeon",
  "Orthopedic Surgeon",
  "Tonsilitis",
  "Alopecia",
  "Gynecologist",
  "Wisdom Tooth Extraction",
  "Coronary Artery Disease",
  "Diabetic Foot",
  "Penis",
  "Pelvis",
  "Pediatrician",
  "Tonsillectomy",
  "Pemphigus Vulgaris",
  "Transplant",
  "Nephrotic Syndrome",
  "Cholangiocarcinoma",
  "Ligament",
  "Vaginal Cancer",
  "Hysteroscopy",
  "Vision Problem",
  "Neonatologist",
  "Laparoscopic Surgery",
  "Breast",
  "Chickenpox Vaccine",
  "Huntingtons Disease",
  "Surgical Oncologist",
  "Ultrasound",
  "Peritoneal Dialysis",
  "Pulmonary Atresia",
  "Keyhole Angioplasty",
  "Foot Sprain",
  "Polymyalgia Rheumatica",
  "Gastroesophageal Reflux",
  "Phimosis",
  "Medical Abortion",
  "Blood Pressure",
  "Stitches",
  "Hiv",
  "Mouth",
  "Orthopedician",
  "Slip Disc",
  "Hand Pain",
  "Ankylosing Spondylitis",
  "Difficulty In Swallowing",
  "Ganglion Cyst",
  "Toe Pain",
  "Joint Pain",
  "Difficulty Climbing Stairs",
  "Muscle Pain",
  "Scoliosis",
  "Tingling Sensation",
  "Arm Pain",
  "Neck Stiffness",
  "Heart Murmur",
  "Knee Swelling",
  "Leg Numbness",
  "Foot Pain",
  "Hip Replacement",
  "Knee Pain",
  "Low Back Pain",
  "Spine Surgery",
  "Gout",
  "Acl Reconstruction Surgery",
  "Physiotherapy",
  "Leg Swelling",
  "Knee Replacement",
  "Difficulty Walking",
  "Rheumatoid Arthritis",
  "Slip Disc Treatment",
  "Swollen Foot",
  "Ankle Pain",
  "Swelling Of Hand",
  "Paralysis",
  "Hip Pain",
  "Swollen Leg",
  "Irritability",
  "Fear",
  "Loneliness",
  "Crying",
  "Unable to sleep",
  "Adhd",
  "Stammered Speech",
  "Sleepiness",
  "Dementia",
  "Difficult To Awaken",
  "Brain Tumor",
  "Seizures",
  "Stroke",
  "Brain Surgery",
  "Excessive Sweating",
  "Parkinsons Disease",
  "Hysterectomy",
  "Vaginal Delivery",
  "Vaginal Itching",
  "Vaginal Bleeding",
  "Vaginal Pain",
  "Ovarian Cyst",
  "Fibroadenoma",
  "Endometriosis",
  "Pain During periods",
  "Vaginal Discharge",
  "Pregnancy",
  "Vaginal Swelling",
  "Ivf Treatment",
  "Breast Cancer Treatment",
  "Breast Cancer",
  "Vaginal Burning",
  "Gallbladder Stones Removal",
  "Mucus",
  "Anal Pain",
  "Gastric Banding Surgery",
  "Hemorrhoids",
  "Pancreas Transplant",
  "Colon Cancer",
  "Hernia",
  "Fatty Liver Disease",
  "Burning In Stomach",
  "Hepatitis B",
  "Lactose Intolerance",
  "Acl Tear",
  "Cataracts",
  "Dry Eyes",
  "Halos Around Light",
  "Bleeding From Eye",
  "Eye Sight Changes",
  "Glaucoma",
  "Eye Redness",
  "Cataract Surgery",
  "Puffy Eyes",
  "Itchy Eyes",
  "Lasik Eye Surgery",
  "Pain In Eye",
  "Poor Vision",
  "Heart Bypass Surgery",
  "Cardiac Arrest",
  "Open Heart Surgery",
  "Angioplasty",
  "Heart Attack",
  "Coronary Artery Bypass Graft Surgery",
  "Weak Heart",
  "Fast beating heart",
  "Heart Pain",
  "Decay In Tooth",
  "Bleeding Tooth",
  "Mouth Breathing",
  "Mouth Ulcer",
  "Bad Breath",
  "Excessive Salivation",
  "Tooth Fracture",
  "Pain In Gums",
  "Ear Pain",
  "Difficulty Eating",
  "Nose Bleeding",
  "Wheezing",
  "Hearing Loss",
  "Throat Pain",
  "Itching In Ear",
  "Lumps Under Skin",
  "Lump In Chest",
  "Leukemia",
  "Lung Cancer",
  "Proton Therapy",
  "Plastic Surgery",
  "Bed Sores",
  "Psoriasis",
  "Skin Blister",
  "Scar",
  "Skin Rashes",
  "Acne",
  "Pain after vaginal birth",
  "Pregnancy Problems",
  "Difficulty Breathing",
  "Bronchitis",
  "Lung Transplantation",
  "Tuberculosis",
  "Bone Marrow Transplant",
  "Kidney Transplant",
  "Liver Transplant",
  "Gynecomastia",
  "Unexplained Weight Gain",
  "Stalled Height",
  "Umbilical Hernia",
  "Toothache",
  "Fever",
  "Chickenpox",
  "Autism",
  "Bedwetting",
  "Down Syndrome",
  "Erectile Dysfunction",
  "Fertility",
  "Sexually Transmitted Infection",
  "Fertility Treatment",
  "Not Eating Food",
  "Hydrocele",
  "Lesions On Penis",
  "Premature Ejaculation",
  "Unprotected Sex",
  "Chordee",
  "Premature Greying Of Hair",
  "Excessive Hair Growth",
  "Hair Loss Treatments",
  "Hair Loss",
  "Burning Sensation While Urinating",
  "Radiation Therapy",
  "Acute Renal Failure",
  "Hemodialysis",
  "Liver Cirrhosis",
  "Hepatitis A",
  "Rabies",
  "Pollen Allergy",
  "hiv",
  "hiatal hernia",
  "hidradenitis suppurativa",
  "high cholesterol",
  "high risk pregnancy",
  "high blood pressure",
  "high thyroid levels",
  "hip arthritis",
  "hip arthroscopy",
  "hip arthroplasty",
  "hip bursitis",
  "hip fracture",
  "hip labral tear",
  "hip dislocation",
  "hip decompression",
  "hip damage",
  "hip injury",
  "hip replacement",
  "hip resurfacing",
  "hip revision",
  "hip pinning",
  "hip pain",
  "hirsutism",
  "hirschsprung disease",
  "histoplasmosis",
  "hiccups",
  "back bone fracture",
  "back sprain",
  "back pain",
  "back itching",
  "bacterial endocarditis",
  "bacterial keratitis",
  "bacterial vaginosis",
  "balloon sinuplasty",
  "balloon mitral valvotomy",
  "balanoposthitis",
  "barth syndrome",
  "bartholins cyst",
  "bartholins abscess",
  "bartter syndrome",
  "basal cell cancer",
  "basal cell carcinomas",
  "batten disease",
  "baby bottle tooth decay",
  "babinski sign",
  "bakers cyst",
  "bad breath",
  "abstract hypoplastic thumb",
  "abscess of vulva",
  "absence of menstruation",
  "abdominoplasty",
  "abdominoperineal excision",
  "abdominal colectomy",
  "abdominal aortic aneurysm",
  "abdominal distension",
  "abdominal pain",
  "abdomonial lap adhesiolysis",
  "abortion",
  "abnormal urine",
  "abnormal walking",
  "asbestosis",
  "ascites",
  "ascitis",
  "ascending aortic aneurysm",
  "asperger syndrome",
  "asthma",
  "astigmatism",
  "astragalectomy",
  "aqueous humor",
  "aerophagia",
  "achalasia",
  "achilles tendinitis",
  "achilles tendon rupture",
  "achilles tendon repair surgery",
  "achilles tendonitis",
  "acid lipase disease",
  "acid reflux",
  "acid-suppressing treatment",
  "acl tear",
  "acl reconstruction surgery",
  "acne",
  "acute disseminated encephalomyelitis",
  "acute myeloid leukemia",
  "acute renal failure",
  "acute stress reaction",
  "acoustic neuroma",
  "acoustic schwannoma",
  "acanthosis nigricans",
  "accident",
  "acromegaly",
  "acromioplasty",
  "actinic keratoses",
  "ace inhibitors",
  "adenoid hypertrophy",
  "adenoid removal",
  "adhd",
  "adrenal disorders",
  "adrenal tumor",
  "adrenalectomy",
  "adrenocortical carcinoma",
  "adrenoleukodystrophy",
  "adnexa of uterus",
  "aflibercept",
  "age related macular degeneration",
  "agenesis of the corpus callosum",
  "aging",
  "agnosia",
  "agoraphobia",
  "aggressive behaviour",
  "agressive behaviour",
  "aicardi goutieres syndrome disorder",
  "aicardi syndrome",
  "albinism",
  "alcohol withdrawal",
  "alcohol septal ablation",
  "alcoholic hepatitis",
  "alcoholic liver disease",
  "alcoholism",
  "alchohol withdrawal",
  "alexander disease",
  "alopecia",
  "alpers disease",
  "alport syndrome",
  "alpha blockers",
  "als",
  "alternating hemiplegia",
  "alzheimers disease",
  "allergic vaginitis",
  "allogenic transplant",
  "alkali therapy",
  "amblyopia",
  "amniocentesis",
  "amputation",
  "anal cancer",
  "anal fissure",
  "anal sphincterotomy",
  "anal itching",
  "anagen effluvium",
  "anaphylaxis",
  "anaplastic astrocytoma",
  "androgen deficiency",
  "andropause",
  "anemia",
  "anencephaly",
  "aneurysm",
  "aneursym",
  "angelman syndrome",
  "anger issues",
  "angina",
  "angioma",
  "angioedema",
  "angioplasty",
  "anisocoria",
  "ankle fracture",
  "ankle fusion",
  "ankle ligament tear",
  "ankle sprain",
  "ankle stiffness",
  "ankle arthroscopy",
  "ankle replacement surgery",
  "ankle redness",
  "ankle robotic surgey",
  "ankle keyhole surgery",
  "ankle edema",
  "ankle pain",
  "ankylosing spondylitis",
  "anorectal malformations",
  "anorectal abscess",
  "anorectal dysfunction",
  "anorexia",
  "anthrax",
  "antiphospholipid syndrome",
  "antiplatelet medication",
  "antisocial personality disorder",
  "antisocial behavior",
  "antibiotics",
  "anti-vegf medication",
  "antihistamines",
  "anti itching drugs",
  "anti inflammatory",
  "anti angiogenesis therapy",
  "anticholinergics",
  "antivirals",
  "antidepressant medications",
  "anterior cervical discectomy",
  "ant-inflammatory drugs",
  "anxiety",
  "anhedonia",
  "aortic coarctation",
  "aortic valve disease",
  "aortic valve replacement",
  "aortic dissection",
  "aorta repair",
  "aphasia",
  "aphonia",
  "appendicitis",
  "appendectomy",
  "apraxia",
  "apathy",
  "apnea",
  "arachnoid cysts",
  "arachnoiditis",
  "arrhythmia",
  "arteriovenous malformation",
  "arterial thromboendarterectomy",
  "arthritis",
  "arthrodesis",
  "arthroplasty",
  "arthrography",
  "arthoscopy",
  "artificial fertilization",
  "arm lift",
  "arm fracture open reduction",
  "arm pain",
  "arm stiffness",
  "arms robotic surgey",
  "arms keyhole surgery",
  "armpin damage",
  "armpit damage",
  "ataxia",
  "atopic dermatitis",
  "atrial fibrillation",
  "atrial flutter",
  "atrial septal defect",
  "atrial septostomy",
  "atrial tachycardia",
  "atrioventricular canal defect",
  "atrioventricular node ablation",
  "autism",
  "autoimmune hepatitis",
  "autologous transplant",
  "aura",
  "auriculectomy",
  "augmentation cystoplasty",
  "avastin",
  "avulsed tooth",
  "avoidant personality disorder",
  "behcets disease",
  "benign essential blepharospasm",
  "benign prostatic hyperplasia",
  "benign positional vertigo",
  "benign breast enlargement",
  "beta-blocker medication",
  "beauty products allergy",
  "bedwetting",
  "bed sores",
  "bile duct cancer",
  "bile acid binding resins",
  "biliary atresia",
  "biliary fibrosis",
  "biliary drainage",
  "binswangers disease",
  "binge eating",
  "bipolar disorder",
  "biopsy of thick skin",
  "birth control treatment",
  "birth defect",
  "birthmark",
  "black eye",
  "black fever",
  "black out",
  "black stools",
  "blackheads",
  "bladder cancer",
  "bladder exstrophy",
  "bladder neck contracture",
  "bladder not emptying completely",
  "bladder distention",
  "blepharitis",
  "blepharoplasty",
  "blemish",
  "bleeding after intercourse",
  "bleeding eye",
  "bleeding from ear",
  "bleeding from elbow",
  "bleeding from eye",
  "bleeding from nipple",
  "bleeding from face",
  "bleeding from feet",
  "bleeding from fingers",
  "bleeding from forehead",
  "bleeding from hands",
  "bleeding from head",
  "bleeding from shoulder",
  "bleeding from skin",
  "bleeding from stomach",
  "bleeding from thumb",
  "bleeding from toe",
  "bleeding from tongue",
  "bleeding from veins",
  "bleeding from wrist",
  "bleeding gums",
  "bleeding tooth",
  "bleeding during pregnancy",
  "blocked tear duct",
  "blocked fallopian tube",
  "blocked nose",
  "blocked pores",
  "bloodshot eye",
  "blood cancer treatment",
  "blood protein controllers",
  "blood thinners",
  "blood in stool",
  "blood in urine",
  "blood in mucus",
  "bloating",
  "blurriness",
  "blurred vision",
  "blue colored skin",
  "blisters on back",
  "blisters on chest",
  "blisters on leg",
  "bone cancer",
  "bone infection",
  "bone graft",
  "bone marrow transplant",
  "bone marrow cancer treatment",
  "bone robotic surgey",
  "bone keyhole surgery",
  "bone fracture",
  "bone loss",
  "botulism",
  "botox injections",
  "bowens disease",
  "bowel obstruction",
  "bowlegs",
  "borderline personality disorder",
  "body lift",
  "body contouring surgery",
  "body whitening treatment",
  "body aches",
  "body stiffness",
  "bppv",
  "brain aneurysm",
  "brain tumor",
  "brain biopsy",
  "brain surgery",
  "brain robotic surgey",
  "brain keyhole surgery",
  "brain cancer treatment",
  "branch retinal vein occlusion",
  "branchial cyst",
  "brachytherapy",
  "bradycardia",
  "breast cancer",
  "breast cyst",
  "breast milk jaundice",
  "breast magnetic resonance imaging",
  "breast abscess",
  "breast augmentation",
  "breast lift",
  "breast lesion",
  "breast reconstruction",
  "breast reduction",
  "breast robotic surgey",
  "breast keyhole surgery",
  "breast biopsy",
  "breast shape change",
  "breast swelling",
  "breast enlarged",
  "breast engorgement",
  "breast tenderness",
  "breast heavyness",
  "breast-conserving surgery",
  "breastfeeding pain",
  "broken nose",
  "broken finger",
  "broken foot",
  "broken leg",
  "bronchiectasis",
  "bronchitis",
  "bronchiolitis",
  "bronchial thermoplasty",
  "bronchotomy",
  "bronchodilators",
  "brown sequard syndrome",
  "brown spots on tooth",
  "brow lift",
  "bruxism",
  "brugada syndrome",
  "bruise",
  "brittle nails",
  "bubonic plague",
  "bulimia",
  "bulbar palsy",
  "bulging of eyes",
  "bunion",
  "buried penis",
  "burn",
  "bursitis",
  "bursectomy",
  "buttock furuncle",
  "buttock augmentation",
  "buttock burn",
  "buttock pain",
  "bump on head",
  "bumps on skin"
]